[package]
name = "target-generatorv2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
anyhow = "1.0.79"
rayon = {version = "1.8.1", features = []}
clap = {version = "4.4.18", features = ["default"]}
simple_logger = "4.3.3"
log = "0.4.20"
rand = {version = "0.8.5", features = ["default"]}